Repository ansys/pyacp, pull requests merged in 2024-12, with the labels that each got.

#733 Docs: make example thumbnails bigger
  doc/source/_static/custom.css
  doc/source/_static/gallery_thumbnails/sphx_glr_001-materials_thumb.png
  doc/source/_static/gallery_thumbnails/sphx_glr_03-pymechanical-shell-workflow_thumb.png
  doc/source/_static/gallery_thumbnails/sphx_glr_04-pymechanical-solid-workflow_thumb.png
  doc/source/_static/gallery_thumbnails/sphx_glr_05-pymechanical-to-cdb-workflow_thumb.png
  doc/source/_static/gallery_thumbnails/sphx_glr_06-cdb-to-pymechanical-workflow_thumb.png
  doc/source/conf.py
Labels: documentation, enhancement

#745 Added exit call to avoid problems when building documentation
  examples/use_cases/01-optimizing-ply-angles.py
  examples/workflows/01-pymapdl-workflow.py
  examples/workflows/02-advanced-pymapdl-workflow.py
  examples/workflows/05-pymechanical-to-cdb-workflow.py
  src/ansys/acp/core/extras/example_helpers.py
Labels: bug, python

#742 Added danger hint when using windows paths
  doc/source/intro.rst
Labels: documentation
